export const urlGetCustomer = 'http://localhost:8080/getCustomer'
export const urlAddCustomer = 'http://localhost:8080/addCustomer'
export const urlGetTodo = 'http://localhost:8080/getTodo'
export const urlGetTodos = 'http://localhost:8080/getTodos'
export const urlCreateTodo = 'http://localhost:8080/createTodo'
export const urlClearTodos = 'http://localhost:8080/clearTodos'
